runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [macos-latest, ubuntu-latest, windows-latest]
    node: [16]

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: ${{ matrix.node }}
  - uses: pnpm/action-setup@v2.1.0
    with:
      version: 6
  - name: Install dependencies
    run: pnpm i
  - name: Install Playwright
    run: npx playwright install --with-deps
  - name: Run your tests
    run: pnpm test
  - name: Upload test results
    if: always()
    uses: actions/upload-artifact@v2
    with:
      name: playwright-results
      path: test-results
